import React from 'react';
import {
  ChakraProvider,
  Box,
  Heading,
  Text,
  VStack,
  Accordion,
  Divider,
  Flex,
  IconButton,
  useClipboard,
  useToast,
  Tooltip,
  Textarea,
  SimpleGrid,
  AccordionItem, AccordionButton, AccordionPanel, AccordionIcon
} from '@chakra-ui/react';
import { useLocation, Link } from 'react-router-dom';
import NavBar from '../components/NavBar';
import Bubble from '../components/Bubble';
import { CopyIcon, DownloadIcon } from '@chakra-ui/icons';
import jsPDF from 'jspdf';

function ResultsPage() {
  const location = useLocation();
  const results = location.state?.results || {};

  const best_drug = results.best_drug || [];
  const alternatives = results.alternatives || [];
  const genes_and_snps = results.genes_and_snps || {};
  const best_drug_description = results.best_drug_description || [];
  const citations = results.citations || [];
  
  const meds = best_drug.map(r => r["Brand Name"]).join(", ");
  const noteText = `Hi Doctor,

I recently used Virgil, an experimental platform that analyzes genetic information from 23andMe along with other health data to recommend targeted treatments for IBD patients. Based on my results, Virgil has recommended ${meds} because it is predicted to be more effective in helping me achieve remission faster by targeting my specific genetic profile and disease characteristics.

I would appreciate the opportunity to discuss this recommendation with you at our next appointment to understand if this medication could be suitable for my treatment plan.

Thank you for your time and guidance!`;
  const { onCopy } = useClipboard(noteText);
  const toast = useToast();

  const handleDownloadPDF = () => {
    const doc = new jsPDF();

    const lineHeight = 8;
    let y = 10;

    const addWrappedText = (text, fontSize = 12) => {
      doc.setFontSize(fontSize);
      const lines = doc.splitTextToSize(text, 180);
      lines.forEach(line => {
        if (y > 280) {
          doc.addPage();
          y = 10;
        }
        doc.text(line, 15, y);
        y += lineHeight;
      });
      y += lineHeight / 2;
    };

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Note to Doctor', 15, y);
    y += lineHeight;

    doc.setFont('helvetica', 'normal');
    addWrappedText(noteText);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Understanding Your Results', 15, y);
    y += lineHeight;

    doc.setFont('helvetica', 'normal');
    addWrappedText('Your results were chosen...');
    addWrappedText('Your personalized medication recommendations were generated by analyzing your unique genetic profile from your 23andMe data, combined with your health information and clinical research on IBD treatments. This tailored approach aims to help you achieve remission faster and improve your overall treatment outcomes.');
    addWrappedText('Please remember that these recommendations are meant to support discussions with your healthcare provider. They are not a substitute for professional medical advice. We encourage you to share these results with your doctor to explore the best treatment options together.');
    addWrappedText('Expand the medication(s) below to see more specific information. All information is taken from fda.gov/drugs.');

    doc.save('Virgil_IBD_Results.pdf');

    toast({
      title: 'Download Started',
      description: 'Your PDF has been downloaded.',
      status: 'success',
      duration: 3000,
      isClosable: true,
    });
  };

  return (
    <ChakraProvider>
      <Box minH="100vh" bg="#4134bb" display="flex" flexDirection="column" pb={10}>
        <NavBar />

        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexDirection="column"
          px={[4, 6, 8]}
          pt="10vh"
          textAlign="center"
          maxW="90vw"
          mx="auto"
        >
          <VStack spacing={[6, 8]} maxW="100%" w={['100%', '90%', '800px']}>
            <Heading
              size="2xl"
              color="white"
              fontFamily="'Glacial Indifference Bold'"
              textShadow="2px 2px 10px rgba(0, 0, 0, 0.3)"
            >
              Results
            </Heading>

            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              flexDirection="column"
              textAlign="center"
              bg="#675cc4"
              width="100%"
              padding={[4, 6, 8]}
              borderRadius="md"
              boxShadow="lg"
            >
              <Heading
                size="md"
                color="white"
                fontFamily="'Glacial Indifference Bold'"
                mb={6}
              >
                Understanding Your Results
              </Heading>

              <Box
                textAlign="left"
                width="100%"
                mb={8}
                display="flex"
                justifyContent="center"
                flexDirection="column"
                alignItems="center"
                pt={6}
              >
                <Heading
                  size="sm"
                  color="white"
                  fontFamily="'Glacial Indifference Bold'"
                  pb={2}
                  width="100%"
                >
                  Genetic Variants and SNPs
                </Heading>

                {Object.entries(genes_and_snps).map(([gene, snps]) => (
                  <Box key={gene} mb={6} width="100%">
                    <Text mb={3} color="white" fontFamily="'Glacial Indifference Reg'">
                      Your 23andMe data shows a mutation that affects the <b>{gene}</b> gene. The following SNPs were found:
                    </Text>

                    <SimpleGrid columns={[1, 2, 3]} spacing={6} width="100%">
                      {Object.entries(snps).map(([snp, desc]) => (
                        <Box
                          key={snp}
                          p={4}
                          borderRadius="md"
                          border="1px solid"
                          borderColor="whiteAlpha.300"
                          bg="rgba(255, 255, 255, 0.05)"
                          fontFamily="'Glacial Indifference Reg'"
                        >
                          <Accordion allowToggle>
                            <AccordionItem border="none">
                              <AccordionButton px={0} color="purple.300">
                                <Box flex="1" textAlign="left" fontWeight="bold" color="purple.300">
                                  {snp}
                                </Box>
                                <AccordionIcon />
                              </AccordionButton>
                              <AccordionPanel pb={2} fontSize="sm" color="gray.200" whiteSpace="pre-wrap">
                                {desc}
                              </AccordionPanel>
                            </AccordionItem>
                          </Accordion>
                        </Box>
                      ))}
                    </SimpleGrid>
                  </Box>
                ))}

                <Heading
                  size="sm"
                  color="white"
                  fontFamily="'Glacial Indifference Bold'"
                  pb={2}
                  width="100%"
                >
                  Treatment Recommendation
                </Heading>

                <Heading
                  size="sm"
                  color="white"
                  fontFamily="'Glacial Indifference Bold'"
                  pb={2}
                  width="100%"
                >
                  Best Treatment
                </Heading>

                {best_drug_description && best_drug_description.length > 0 ? (
                  <SimpleGrid columns={[1, 2]} spacing={6} width="100%" mb={8}>
                    {best_drug_description.map(({ drug, description }, i) => {

                      const relatedCitations = citations.filter(c => {
                        const bestDrug = c.best_drug;
                        const bestDrugArr = Array.isArray(bestDrug) ? bestDrug : [bestDrug];
                        const drugArr = Array.isArray(drug) ? drug : [drug];
                        return drugArr.some(d => bestDrugArr.includes(d));
                      });

                      return (
                        <Box
                          key={i}
                          p={4}
                          borderRadius="md"
                          border="1px solid"
                          borderColor="whiteAlpha.300"
                          bg="rgba(255, 255, 255, 0.05)"
                          fontFamily="'Glacial Indifference Reg'"
                        >
                          <Text mb={2} color="white">
                            Based on Virgil algorithms, the best treatment for you is <b>{Array.isArray(drug) ? drug.join(", ") : drug}</b>.
                          </Text>

                          <Accordion allowToggle>
                            <AccordionItem border="none">
                              <AccordionButton px={0} fontWeight="bold" color="purple.300">
                                <Box flex="1" textAlign="left" fontFamily="'Glacial Indifference Reg'">
                                  View Description to learn more
                                </Box>
                                <AccordionIcon />
                              </AccordionButton>
                              <AccordionPanel pb={2} fontSize="sm" color="gray.200" whiteSpace="pre-wrap">
                                {description}

                                {relatedCitations.length > 0 && (
                                  <>
                                    <Text fontWeight="bold" mt={4} mb={2} color="white">
                                      Citations:
                                    </Text>
                                    {relatedCitations.map(({ citation }, idx) => (
                                      Array.isArray(citation) ? (
                                        citation.map((url, j) => (
                                          <Text key={`${idx}-${j}`} color="white" mb={1}>
                                            <Link
                                              style={{ textDecoration: 'underline', color: 'white' }}
                                              to={url}
                                              target="_blank"
                                              rel="noopener noreferrer"
                                            >
                                              {url}
                                            </Link>
                                          </Text>
                                        ))
                                      ) : (
                                        <Text key={idx} color="white" mb={1}>
                                          <Link
                                            style={{ textDecoration: 'underline', color: 'white' }}
                                            to={citation}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                          >
                                            {citation}
                                          </Link>
                                        </Text>
                                      )
                                    ))}
                                  </>
                                )}
                              </AccordionPanel>
                            </AccordionItem>
                          </Accordion>
                        </Box>
                      );
                    })}
                  </SimpleGrid>
                ) : (
                  <Text mb={8} color="white" fontFamily="'Glacial Indifference Reg'">
                    Due to the info you shared, the best drug option will not work for you.
                  </Text>
                )}

                <Heading
                  size="sm"
                  color="white"
                  fontFamily="'Glacial Indifference Bold'"
                  pb={2}
                  width="100%"
                >
                  Alternative Treatment
                </Heading>

                {alternatives && alternatives.length > 0 ? (
                  <Text mb={4} color="white" fontFamily="'Glacial Indifference Reg'">
                    Some alternative treatment(s) are {alternatives.map(a => a["Brand Name"]).join(", ")}.
                  </Text>
                ) : (
                  <Text mb={4} color="white" fontFamily="'Glacial Indifference Reg'">
                    Due to the info you shared, alternative treatments are not recommended.
                  </Text>
                )}

                 <Text pt={4} color="white" fontFamily="'Glacial Indifference Reg'">
                  Expand the medication(s) below to see more specific information. All information is taken from{' '}
                  <Link
                    style={{ textDecoration: 'underline' }}
                    to="https://fda.gov/drugs"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    fda.gov/drugs
                  </Link>.
                </Text>
              </Box>

              <Divider pt={6} borderColor="whiteAlpha.300" />


              <>
                <Text pt={6} color="white" fontFamily="'Glacial Indifference Reg'" whiteSpace="pre-wrap">
                  Your personalized medication recommendations were generated by analyzing your unique genetic profile from your 23andMe data, combined with your health information and clinical research on IBD treatments. This tailored approach aims to help you achieve remission faster and improve your overall treatment outcomes.
                </Text>

                <Text pt={2} color="white" fontFamily="'Glacial Indifference Reg'" whiteSpace="pre-wrap">
                  Please remember that these recommendations are meant to support discussions with your healthcare provider. They are not a substitute for professional medical advice. We encourage you to share these results with your doctor to explore the best treatment options together.
                </Text>
              </>

              <Divider pt={6} borderColor="whiteAlpha.300" />

              <Heading
                size="md"
                color="white"
                fontFamily="'Glacial Indifference Bold'"
                pt={6}
                pb={4}
              >
                Next Steps
              </Heading>

              <Flex
                gap={[4, 6]}
                justifyContent="center"
                flexWrap="wrap"
                width="100%"
              >
                <Box
                  display="flex"
                  flexDirection="column"
                  alignItems="stretch"
                  bg="#3b3192"
                  padding={[3, 4]}
                  borderRadius="md"
                  boxShadow="md"
                  flex="1"
                >
                  <Flex justifyContent="space-between" alignItems="center" mb={2}>
                    <Text color="white" fontFamily="'Glacial Indifference Reg'">
                      Copy a note to send to your doctor:
                    </Text>
                    <Tooltip label="Copy note" hasArrow>
                      <IconButton
                        aria-label="Copy note"
                        icon={<CopyIcon />}
                        onClick={() => {
                          onCopy();
                          toast({
                            title: 'Copied!',
                            description: 'The note was copied to clipboard.',
                            status: 'success',
                            duration: 2000,
                            isClosable: true,
                          });
                        }}
                        colorScheme="purple"
                        variant="solid"
                        size="sm"
                      />
                    </Tooltip>
                  </Flex>

                  <Textarea
                    value={noteText}
                    readOnly
                    resize="vertical"
                    height="100px"
                    fontFamily="'Glacial Indifference Reg'"
                    bg="#8a81d6"
                  />
                </Box>

                <Box
                  flexShrink={0}
                  display="flex"
                  alignItems="center"
                  justifyContent="center"
                  color="white"
                  fontFamily="'Glacial Indifference Bold'"
                  fontSize="lg"
                  px={2}
                  userSelect="none"
                >
                  OR
                </Box>

                <Box
                  display="flex"
                  alignItems="center"
                  justifyContent="space-between"
                  bg="#3b3192"
                  padding={[3, 4]}
                  borderRadius="md"
                  boxShadow="md"
                  flex="1"
                  minW={['280px', '300px']}
                  maxW="400px"
                >
                  <Text color="white" fontFamily="'Glacial Indifference Reg'" flex="1">
                    Download a PDF of your Virgil Results.
                  </Text>
                  <Tooltip label="Download PDF" hasArrow>
                    <IconButton
                      aria-label="Download PDF"
                      icon={<DownloadIcon />}
                      onClick={handleDownloadPDF}
                      colorScheme="purple"
                      variant="solid"
                    />
                  </Tooltip>
                </Box>
              </Flex>
            </Box>

            <Heading
              size="md"
              color="white"
              fontFamily="'Glacial Indifference Bold'"
            >
              Recommended Best Treatment
            </Heading>

            {best_drug && best_drug.length > 0 ? (
              <Accordion allowToggle w="100%">
                {best_drug.map((result, index) => (
                  <Bubble key={index} results={result} />
                ))}
              </Accordion>
            ) : (
              <Text color="white" fontFamily="'Glacial Indifference Reg'">
                No results found.
              </Text>
            )}

            <Heading
              size="md"
              color="white"
              fontFamily="'Glacial Indifference Bold'"
            >
              Recommended Alternative Treatment
            </Heading>

            {alternatives && alternatives.length > 0 ? (
              <Accordion allowToggle w="100%">
                {alternatives.map((result, index) => (
                  <Bubble key={index} results={result} />
                ))}
              </Accordion>
            ) : (
              <Text color="white" fontFamily="'Glacial Indifference Reg'">
                No results found.
              </Text>
            )}
          </VStack>
        </Box>
      </Box>
    </ChakraProvider>
  );
}

export default ResultsPage;