import React from 'react';
import {
  ChakraProvider,
  Box,
  Heading,
  Text,
  VStack,
  Accordion,
  Divider,
  Flex,
  IconButton,
  useClipboard,
  useToast,
  Tooltip,
  Textarea,
} from '@chakra-ui/react';
import { useLocation, Link } from 'react-router-dom';
import NavBar from '../components/NavBar';
import Bubble from '../components/Bubble';
import { CopyIcon, DownloadIcon } from '@chakra-ui/icons';

function ResultsPage() {
  const location = useLocation();
  const resultString = location.state?.results || [];
  
  const meds = resultString.map(r => r["Brand Name"]).join(", ");
  const noteText = `Hi Doctor,

I recently used Virgil, an experimental platform that analyzes genetic information from 23andMe along with other health data to recommend targeted treatments for IBD patients. Based on my results, Virgil has recommended ${meds} because it is predicted to be more effective in helping me achieve remission faster by targeting my specific genetic profile and disease characteristics.

I would appreciate the opportunity to discuss this recommendation with you at our next appointment to understand if this medication could be suitable for my treatment plan.

Thank you for your time and guidance!`;
  const { onCopy } = useClipboard(noteText);
  const toast = useToast();


  {/* ADD PDF DOWNLOAD FN*/}
  const handleDownloadPDF = () => {
    toast({
      title: 'Coming Soon',
      description: 'Downloadable PDF is not available yet.',
      status: 'info',
      duration: 3000,
      isClosable: true,
    });
  };

  return (
    <ChakraProvider>
      <Box minH="100vh" bg="#4134bb" display="flex" flexDirection="column" pb={10}>
        <NavBar />

        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          flexDirection="column"
          px={[4, 6, 8]}
          pt="10vh"
          textAlign="center"
          maxW="90vw"
          mx="auto"
        >
          <VStack spacing={[6, 8]} maxW="100%" w={['100%', '90%', '800px']}>
            <Heading
              size="2xl"
              color="white"
              fontFamily="'Glacial Indifference Bold'"
              textShadow="2px 2px 10px rgba(0, 0, 0, 0.3)"
            >
              Results
            </Heading>

            <Box
              display="flex"
              justifyContent="center"
              alignItems="center"
              flexDirection="column"
              textAlign="center"
              bg="#675cc4"
              width="100%"
              padding={[4, 6, 8]}
              borderRadius="md"
              boxShadow="lg"
            >
              <Heading
                size="md"
                color="white"
                fontFamily="'Glacial Indifference Bold'"
              >
                Understanding Your Results
              </Heading>

              <>
                {/* ADD HERE YOUR SPECIFIC GENETIC PROFILE */}
                <Text pt={4} color="white" fontFamily="'Glacial Indifference Reg'" fontWeight="bold">
                  Your results were chosen...
                </Text>

                <Text pt={2} color="white" fontFamily="'Glacial Indifference Reg'" whiteSpace="pre-wrap">
                  Your personalized medication recommendations were generated by analyzing your unique genetic profile from your 23andMe data, combined with your health information and clinical research on IBD treatments. Virgil uses advanced algorithms to identify which medications are likely to be most effective for you based on how your genes influence your disease and response to drugs. This tailored approach aims to help you achieve remission faster and improve your overall treatment outcomes.
                </Text>

                <Text pt={2} color="white" fontFamily="'Glacial Indifference Reg'" whiteSpace="pre-wrap">
                  Please remember that these recommendations are meant to support discussions with your healthcare provider. They are not a substitute for professional medical advice. We encourage you to share these results with your doctor to explore the best treatment options together.
                </Text>
              </>

              <Text pt={4} color="white" fontFamily="'Glacial Indifference Reg'">
                Expand the medication(s) below to see more specific information. All information is taken from{' '}
                <Link
                  style={{ textDecoration: 'underline' }}
                  to="https://fda.gov/drugs"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  fda.gov/drugs
                </Link>.
              </Text>

              <Divider pt={6} borderColor="whiteAlpha.300" />

              <Heading
                size="md"
                color="white"
                fontFamily="'Glacial Indifference Bold'"
                pt={6}
                pb={4}
              >
                Next Steps
              </Heading>

              <Flex
                gap={[4, 6]}
                justifyContent="center"
                flexWrap="wrap"
                width="100%"
              >
                <Box
                  display="flex"
                  flexDirection="column"
                  alignItems="stretch"
                  bg="#3b3192"
                  padding={[3, 4]}
                  borderRadius="md"
                  boxShadow="md"
                  flex="1"
                >
                  <Flex justifyContent="space-between" alignItems="center" mb={2}>
                    <Text color="white" fontFamily="'Glacial Indifference Reg'">
                      Copy a note to send to your doctor:
                    </Text>
                    <Tooltip label="Copy note" hasArrow>
                      <IconButton
                        aria-label="Copy note"
                        icon={<CopyIcon />}
                        onClick={() => {
                          onCopy();
                          toast({
                            title: 'Copied!',
                            description: 'The note was copied to clipboard.',
                            status: 'success',
                            duration: 2000,
                            isClosable: true,
                          });
                        }}
                        colorScheme="purple"
                        variant="solid"
                        size="sm"
                      />
                    </Tooltip>
                  </Flex>

                  <Textarea
                    value={noteText}
                    readOnly
                    resize="vertical"
                    height="100px"
                    fontFamily="'Glacial Indifference Reg'"
                    bg="#8a81d6"
                  />
                </Box>

                <Box
                  flexShrink={0}
                  display="flex"
                  alignItems="center"
                  justifyContent="center"
                  color="white"
                  fontFamily="'Glacial Indifference Bold'"
                  fontSize="lg"
                  px={2}
                  userSelect="none"
                >
                  OR
                </Box>

                <Box
                  display="flex"
                  alignItems="center"
                  justifyContent="space-between"
                  bg="#3b3192"
                  padding={[3, 4]}
                  borderRadius="md"
                  boxShadow="md"
                  flex="1"
                  minW={['280px', '300px']}
                  maxW="400px"
                >
                  <Text color="white" fontFamily="'Glacial Indifference Reg'" flex="1">
                    Download a PDF of your Virgil Results.
                  </Text>
                  <Tooltip label="Download PDF" hasArrow>
                    <IconButton
                      aria-label="Download PDF"
                      icon={<DownloadIcon />}
                      onClick={handleDownloadPDF}
                      colorScheme="purple"
                      variant="solid"
                    />
                  </Tooltip>
                </Box>
              </Flex>
            </Box>

            <Heading
              size="md"
              color="white"
              fontFamily="'Glacial Indifference Bold'"
            >
              Recommended Medications
            </Heading>

            {resultString && resultString.length > 0 ? (
              <Accordion allowToggle w="100%">
                {resultString.map((result, index) => (
                  <Bubble key={index} results={result} />
                ))}
              </Accordion>
            ) : (
              <Text color="white" fontFamily="'Glacial Indifference Reg'">
                No results found.
              </Text>
            )}
          </VStack>
        </Box>
      </Box>
    </ChakraProvider>
  );
}

export default ResultsPage;